platformName : Android
# 安卓版本
platformVersion : 5.1.1
# 可以随便写，主要是为了区分手机
deviceName : emulator-5554
# 测试app的包名
appPackage : com.android.settings
# 测试app的activity名
appActivity : .Settings
# 支持unicode键盘，输入中文时需要
unicodeKeyboard : true
resetKeyboard : true